### ISSUE TITLE
Σελίδα με το πρόγραμμα μαθημάτων σε yaml, markdown format

### ISSUE THREAD

**Issue by spiroskatsampiris** [upatras-hci/site#104]

**Comment by epidrome** [comment]
@spiroskatsampiris 


1. επειδή αυτό είναι σημαντικό καλό θα ήταν να εμπλακούν και κάποιοι ακόμη, 

2. επίσης καλό θα ήταν πριν γίνει αίτημα να γίνει συζήτηση εδώ ή/και στο αποθετήριο σου αναφορικά με την οργάνωση του αρχείου καθώς και του html layout

**Comment by epidrome** [comment]
do you have any update on this?

i would like to see at least a couple more people getting involved, plz
