### ISSUE TITLE
Τεκμηρίωση για την διαδικασία συνεισφοράς

### ISSUE THREAD

**Issue by vagg777** [upatras-hci/site#105]
Α file with contribution guidelines to the project repository's root folder. When someone opens a pull request or creates an issue, they will see a link to that file.

**Comment by epidrome** [comment]
Please consider the following issues for the new files:

- [x] add the most common errors, e.g., `closes #No`, news should have dates as part of the file name

- [x] consider creating a link to style guide for each file type, e.g., people, course, news, schedule

- [ ] co-ordinate with #110 #104

- [ ] move the file to .github?

**Comment by epidrome** [comment]
i have converted the points above to checks and added one more point to consider above and i am inviting the respective collaborators @spiroskatsampiris @tgeorgako in order to co-ordinate efforts
