### ISSUE TITLE
Προσθήκη μορφότυπων για τα θέματα και τα αιτήματα συνεισφοράς

### ISSUE THREAD

**Issue by tgeorgako** [upatras-hci/site#110]
Creation of templates for issues and pull requests

**Comment by epidrome** [comment]
@tgeorgako 

1. επειδή αυτό είναι σημαντικό καλό θα ήταν να εμπλακούν και κάποιοι ακόμη,

2. επίσης καλό θα ήταν πριν γίνει αίτημα να γίνει συζήτηση εδώ ή/και στο αποθετήριο σου αναφορικά με την οργάνωση του αρχείου, π.χ. υπάρχουν πολλά έτοιμα μορφότυπα για αυτά τα αρχεία καλό θα ήταν να βασιστούμε κάπου

**Comment by epidrome** [comment]
do you have any update on this?

i would like to see at least a couple more people getting involved, plz
