### ISSUE TITLE
Μεταφορά-επεξεργασία των layouts, includes (courses, people, posts)

### ISSUE THREAD

**Issue by mouliasteo** [upatras-hci/site#114]

**Comment by epidrome** [comment]
@mouliasteo 

1. επειδή αυτό είναι σημαντικό καλό θα ήταν να εμπλακούν και κάποιοι ακόμη,

2. επίσης καλό θα ήταν πριν γίνει αίτημα να γίνει συζήτηση εδώ ή/και στο αποθετήριο σου αναφορικά με κάθε αρχείο

**Comment by moya10** [comment]
fork this https://github.com/moya10/site-gr
