### ISSUE TITLE
Αρχιτεκτονική της πληροφορίας για τις ανακοινώσεις (κατηγορίες, ετικέτες)

### ISSUE THREAD

**Issue by irozarkadoula** [upatras-hci/site#117]

**Comment by epidrome** [comment]
@irozarkadoula 

1. επειδή αυτό είναι σημαντικό καλό θα ήταν να εμπλακούν και κάποιοι ακόμη,

2. επίσης καλό θα ήταν πριν γίνει αίτημα να γίνει συζήτηση εδώ ή/και στο αποθετήριο σου αναφορικά με κάθε αρχείο-κατηγορία-ετικέτα
