### ISSUE TITLE
Fork the following project 

### ISSUE THREAD

**Issue by moya10** [upatras-hci/site#121]
https://github.com/moya10/site-gr

αφου κανετε fork μπορω να σας κανω  assignees και να επεξεργαζομαστε ολοι μαζι, πανω σε αυτο πριν το παραδωσουμε...

**Comment by epidrome** [comment]
μπράβο! φαίνεται πως έχεις υλοποιήσει μόνη σου τα πιο σημαντικά ζητούμενα και έχεις λειτουργική ιστοσελίδα, αλλά σε ένα μάθημα συνεργατικών συστημάτων και την αντίστοιχη εργασία η προσδοκία ήταν όλο αυτό να είναι συνεργατικό, φυσικά, η ευθύνη αυτή είναι συλλογική

το βασικό σχόλιο βελτίωσης είναι πως η υλοποίηση που έκανες λειτουργεί ανεξάρτητα από το αποθετήριο εδώ, οπότε δεν υπάρχει εύκολος τρόπος συγχρονισμού, το οποίο είναι ένα σημαντικό τεχνικό ζητούμενο σε συνεργατικά έργα.
