### ISSUE TITLE
New Professors

### ISSUE THREAD

**Issue by tkoutropoulou** [upatras-hci/site#131]
Hi all, 
We have to add the names of the new professors. 

Here is a list with the new ones: 
Christos Sintoris & Nikos Fakotakis (added by Alex)
Pavlos Peppas
Christos Fidas
Andreas Komninos
Sonia Malefaki

Please confirm in order to add them. 
Thanks.

**Comment by irozag** [comment]
ok, I'll try to do the example that the professor shows us to create a page with professors. or to add lessons.  is that ok?

**Comment by tkoutropoulou** [comment]
From my side, yes!
