### ISSUE TITLE
update layout and add index page for courses

### ISSUE THREAD

**Issue by irozag** [upatras-hci/site#143]
I will add a page layout for courses and connect it with the site

**Comment by epidrome** [comment]
layouts are working already
https://upatras-hci.github.io/site/courses/cscw/

maybe it is worth adding the courses index page that lists all courses

**Comment by irozag** [comment]
I add an course.md to the page folder. I cannot check if it is working. Could you please check it?

**Comment by epidrome** [comment]
thanks! i have added @moya10 as reviewer and will merge as soon as we get some comments and feedback by the reviewer and/or other members of the team

**Comment by irozag** [comment]
I try again to run it locally, but I have troubles with the JSON versions. I have just updated to "Big Sur". I hope I will manage to run it locally, I will try again next week. If this goes well, I could check it on my own. Till then, I am not sure what I upload, so please have a look.
