### ISSUE TITLE
Help needed to run Jekyll locally.  

### ISSUE THREAD

**Issue by irozag** [upatras-hci/site#149]
I step again in front of a bug (attached link), and I need help to run Jekyll locally. 
https://github.com/github/pages-gem/issues/752

![image](https://user-images.githubusercontent.com/13382528/104848972-0e491d00-58f0-11eb-8600-68d7cd8aa2a9.png)

**Comment by epidrome** [comment]
δεν νομίζω ότι είναι μπαγκ, σίγουρα δεν θέλει σουντο

θέλει προσοχή να έχεις πρόσφατη έκδοση ρουμπι, 

και όχι αυτήν του μακ, εδώ βοηθάει το rbenv

αν το ρουμπι είναι το σωστό τότε οι εντολές είναι

> gem install bundler jekyll
> bundle install
> bundle exec jekyll serve
