### ISSUE TITLE
Collaborating institutions in the _news file

### ISSUE THREAD

**Issue by MariaKoutroumani** [upatras-hci/site#6]
Description of the collaborating institutions that run HCI Master

**Comment by epidrome** [comment]
the `_news` folder should be used only for news, so i created the `partners.md` inside a new folder `_pages`, where static pages should reside

please consider this guide:
https://mmistakes.github.io/minimal-mistakes/docs/pages/

in the meantime i suggest you open an issue for an easier task, such as a course
